language: php
dist: trusty
sudo: false

matrix:
  include:
    - php: 7.2
      env: FRAMEWORK_VERSION=laravel/framework:5.6.*
    - php: 7.2
      env: FRAMEWORK_VERSION=laravel/lumen-framework:5.6.*

before_install:
  - pecl install swoole

install:
  - composer require "${FRAMEWORK_VERSION}" --no-update -n
  - travis_retry composer install --no-suggest --prefer-dist -n -o

script: vendor/bin/phpunit