dist: trusty
sudo: false

language: php

php:
  - '7.1'
  - '7.2'

before_install:
  - printf "\n" | pecl install swoole

install:
  - travis_retry composer install --no-suggest --prefer-dist -n -o

script: vendor/bin/phpunit